name: Jekyll build
on:
  schedule: # Run workflow automatically
    - cron: '* * 1 * *' # Runs every months
  workflow_dispatch: 

jobs:
  jekyll:
    name: Build and store Jekyll site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ“¥
        uses: actions/checkout@v2.3.4
        with:
          lfs: true
          fetch-depth: 1

      - name: Build âš™ï¸
        uses: vivi90/jekyll-minimal-action@v1.1.0
        with:
          command: jekyll build

      - name: Store ğŸ“¦
        uses: actions/upload-artifact@v2.2.4
        if: success()
        with:
          name: site
          path: _site
